#!/bin/sh

### BEGIN INIT INFO
# Provides:        babymonitor
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start babymonitor daemon
### END INIT INFO


PATH="/usr/local/bin:/usr/bin:${PATH}"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting babymonitor"
    cd "/opt/babymonitor"
    su babymonitor -s /bin/bash -c "npm start"
    ;;
  stop)
    echo "Stopping babymonitor"
    cd "/opt/babymonitor"
    su babymonitor -s /bin/bash -c "npm stop"
    ;;
  *)
    echo "Usage: /etc/init.d/babymonitor {start|stop}"
    exit 1
    ;;
esac

exit 0
