# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'puphpet/debian75-x64'

  config.ssh.forward_agent = true
  config.vm.synced_folder '../../', '/home/vagrant/workspace/src/github.com/baby-tech/babymonitor'
  config.vm.network 'forwarded_port', guest: 8888, host: 8888

  config.vm.provision 'shell', inline: 'apt-get install update'
  config.vm.provision 'shell', inline: 'apt-get install -y imagemagick vim'
  config.vm.provision 'shell', inline: 'mkdir /home/vagrant/bin'
  config.vm.provision 'shell', inline: 'ln -s /home/vagrant/workspace/src/github.com/baby-tech/babymonitor/infra/stubs/bin/raspistill /home/vagrant/bin/raspistill'

  config.vm.provision 'shell', inline: 'curl --fail -L https://github.com/optiver/courier/releases/download/1.1.0/courier.gz > /tmp/courier.gz'
  config.vm.provision 'shell', inline: 'mkdir -p /opt/bin'
  config.vm.provision 'shell', inline: 'gunzip -f /tmp/courier.gz'
  config.vm.provision 'shell', inline: 'mv /tmp/courier /opt/bin/courier'
  config.vm.provision 'shell', inline: 'chmod +x /opt/bin/courier'

  config.vm.provision 'shell', inline: 'curl --fail -L https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz > /tmp/go1.7.1.linux-amd64.tar.gz'
  config.vm.provision 'shell', inline: 'tar -C /usr/local -zxv -f /tmp/go1.7.1.linux-amd64.tar.gz'
  config.vm.provision 'shell', inline: 'echo "export GOPATH=/home/vagrant/workspace" >> /home/vagrant/.profile'

  config.vm.provision 'shell', inline: 'echo "export PATH=$PATH:/usr/local/go/bin:/opt/bin:~/bin" >> /home/vagrant/.profile'
end
