#!/bin/bash

# Create the needed user. It needs to be 'babymonitor'
adduser --system babymonitor

# Change all files to be owned by this user
chown -R babymonitor /opt/baby-monitor
chown -R root:root /etc/init.d/baby-monitor

# Set the appropriate init scripts
update-rc.d -f baby-monitor defaults

# Start the services!
service baby-monitor start
