#!/bin/bash

# Create the needed user. It needs to be 'babymonitor'
useradd -r -d /opt/baby-monitor -s /bin/false babymonitor

# Change all files to be owned by this user
chown -R babymonitor /opt/baby-monitor
chown -R root:root /etc/init.d/baby-monitor

# Set the appropriate init scripts
update-rc.d -f baby-monitor defaults

# Install app dependencies
cd /opt/baby-monitor
su babymonitor -s /bin/bash -c "npm install --production"

# Start the services!
service baby-monitor start
