#!/bin/bash

# Stop the appserver:
service baby-monitor stop || true

#Remove the user
userdel babymonitor

# Remove installed app dependencies
rm -rf /opt/baby-monitor/images/*
rm -rf /opt/baby-monitor/node_modules
rm -rf /opt/baby-monitor/.forever
rm -rf /opt/baby-monitor/.node-gyp
rm -rf /opt/baby-monitor/.npm
