# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder '../', '/home/vagrant/workspace'
  config.ssh.forward_agent = true
  config.berkshelf.enabled = true
  config.vm.provision :shell, :inline => 'sudo apt-get update'
  config.vm.provision 'chef_solo' do |chef|
    chef.run_list = [
      'recipe[babymonitor::packages]',
    ]
  end
  config.vm.provision :shell, :inline => "echo -e '#{File.read("#{Dir.home}/.gitconfig")}' > '/home/vagrant/.gitconfig'" if File.exist?("#{Dir.home}/.gitconfig")
end
