#!/bin/sh

### BEGIN INIT INFO
# Provides:        baby-monitor
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start baby-monitor daemon
### END INIT INFO


PATH="/opt/baby-monitor/:/usr/local/bin:/usr/bin:${PATH}"

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting baby-monitor"
    nohup node /opt/baby-monitor/app.js & # Refactor to use forever
    ;;
  stop)
    echo "Stopping baby-monitor"
    echo "Actually, this hasn't been implemented yet"
    ;;
  *)
    echo "Usage: /etc/init.d/baby-monitor {start|stop}"
    exit 1
    ;;
esac

exit 0
