#!/bin/bash
useradd -r -d /opt/babymonitor -s /bin/false -G video babymonitor
chown -R babymonitor /opt/babymonitor
service babymonitor start
systemctl enable /etc/systemd/system/babymonitor.service
systemctl start babymonitor.service
